apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-i0cw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-i0cw@sha256:10ff9eec01cec879bc21f06f4a9432e64af17e597bd1159bf47766b291e305c2
        name: my-nodejs
        resources: {}
status: {}
